fix: NoMethodError: undefined method `exists?' for class File
After upgrading to vagrant 2.4.3, noticed the following error on vagrant comands:
`Message: NoMethodError: undefined method `exists?' for class File`
Starting in Ruby 3.2.0 the exists? (pluralized) alias for exist? seems to has been removed.
With Ruby 3.2.0, be sure to use the singular-form exist?