fix: undefined method `exists?' for class File (NoMethodError) in vbguest
Removed vagrant-vbgurest plugin because it is using old Ruby 'exists' plural
form instead of singular form, but development has ended, so author will not fix
this error.

Refs: #5